name: CLUSTER_COMPONENTS

on:
  workflow_dispatch:

jobs:
  components:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get vars from tfvars
      run: |
        echo "cluster_name=$(grep -oP 'cluster_name\s*=\s*"\K[^"]+' infra/terraform/app/terraform.tfvars)" >> $GITHUB_ENV
        echo "region=$(grep -oP 'region\s*=\s*"\K[^"]+' infra/terraform/app/terraform.tfvars)" >> $GITHUB_ENV
        
    - name: Set up awscli
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
  
    - name: Set up helm
      uses: azure/setup-helm@v4.2.0

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
        eksctl version

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Connect to cluster
      run: |
        aws eks update-kubeconfig --region ${{ env.region }} --name ${{ env.cluster_name }}

    - name: Add aws Load balancer controller
      run: |
        eksctl utils associate-iam-oidc-provider --region=${{ env.region }} --cluster=${{ env.cluster_name }} --approve
        eksctl delete iamserviceaccount --cluster=${{ env.cluster_name }} --namespace=kube-system --name=aws-load-balancer-controller
        eksctl create iamserviceaccount --cluster=${{ env.cluster_name }} --namespace=kube-system --name=aws-load-balancer-controller --role-name AmazonEKSLoadBalancerControllerRole --attach-policy-arn=$(aws iam list-policies --query "Policies[?PolicyName=='LoadBalancerPolicy'].Arn" --output text) --approve --override-existing-serviceaccounts

        helm repo add eks https://aws.github.io/eks-charts
        helm repo update
        helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system --set clusterName=${{ env.cluster_name }} --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region=${{ env.region }} --set vpcId=$(aws ec2 describe-vpcs --filters "Name=isDefault,Values=true" --query "Vpcs[0].VpcId" --output text)

    - name: Add ingress-nginx
      working-directory: infra/charts/ingress-nginx
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace -f ingress-values.yaml
